# Generated by Django 6.0.1 on 2026-01-25 00:06

import django.db.models.deletion
import django.db.models.functions.datetime
import v1.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('company', 'Company'), ('control', 'Control')], default='company', max_length=20)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('registration', 'Registration'), ('check-in', 'Check-In'), ('check-out', 'Check-Out')], max_length=20)),
                ('timestamp', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('user_control', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checks_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'checks',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='v1.company'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('date_begin', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('close', 'Close'), ('pending', 'Pending')], db_default='pending', max_length=10)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='EventsStaff',
            fields=[
                ('id', models.CharField(default=v1.utils.generate_nano_id, editable=False, max_length=21, primary_key=True, serialize=False)),
                ('staff_cpf', models.CharField(max_length=11)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_staffs', to='v1.event')),
                ('registration_check', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_staff_entry', to='v1.check')),
            ],
            options={
                'db_table': 'events_staff',
            },
        ),
        migrations.AddField(
            model_name='check',
            name='events_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks_history', to='v1.eventsstaff'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date_begin', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('close', 'Close'), ('pending', 'Pending')], db_default='pending', max_length=10)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='v1.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='v1.project'),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='v1.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staffs',
                'unique_together': {('company', 'cpf')},
            },
        ),
        migrations.AddField(
            model_name='eventsstaff',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.staff'),
        ),
        migrations.CreateModel(
            name='UserInvite',
            fields=[
                ('id', models.CharField(default=v1.utils.generate_nano_id, editable=False, max_length=21, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('company', 'Company'), ('control', 'Control')], max_length=20)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('expires_at', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites_created', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invite_used', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_invites',
            },
        ),
        migrations.CreateModel(
            name='EventsCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('production', 'Production'), ('service', 'Service')], max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.company')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participating_companies', to='v1.event')),
            ],
            options={
                'db_table': 'events_company',
                'unique_together': {('event', 'company')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='eventsstaff',
            unique_together={('event', 'staff_cpf')},
        ),
    ]
