# Generated by Django 6.0 on 2026-01-30 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_eventscompany_staff_limit_alter_event_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
