# Generated by Django 6.0 on 2026-01-31 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_remove_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
